# Write your MySQL query statement below
SELECT V.CUSTOMER_ID, COUNT(CUSTOMER_ID) AS COUNT_NO_TRANS FROM Visits AS V
LEFT JOIN Transactions AS T
ON V.VISIT_ID = T.VISIT_ID WHERE V.VISIT_ID NOT IN(SELECT VISIT_ID FROM TRANSACTIONS)
GROUP BY V.CUSTOMER_ID;